extends:
  - airbnb
  - plugin:prettier/recommended
  - prettier/react

parser: babel-eslint

parserOptions:
  ecmaVersion: 6

env:
  browser: true
  node: true
  es6: true

globals:
  __DEV__: true

rules:
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  quotes: [2, 'single']
  no-console: 0
  no-use-before-define: 0
  no-useless-concat: 0
  import/prefer-default-export: 0

  no-unused-vars: ['warn']
  react/no-unused-state: ['warn']

  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      arrowParens: avoid
      printWidth: 100
